### ISSUE TITLE
Rename takes path relative to shell directory instead of current file directory

### ISSUE THREAD

**Issue by gmtek** [tpope/vim-eunuch#114]
Run
```sh
mkdir -p foo/bar/test && touch foo/bar/test/index.md
cd foo/bar
nvim test/index.md
:Rename ../index2.md
```

expected: file renamed to `foo/bar/index2.md`. As the doc says relative path to current file
actual: file renamed to `foo/index2.md`. path is relative to current shell directory

**Comment by hauleth** [comment]
Yeah, I have beed bitten by that. I think that it worked properly in the past.

**Comment by tpope** [comment]
The current behavior is intended. It mirrors commands like `:find`, which drops it's special `'path'` based behavior and reverts to the current working directory for `./` and `../` paths. I'm disinclined to change it, but will think on it a bit before closing.

**Comment by tmillr** [comment]
This one got me yesterday. At the very least, this should be documented IMO (or added to the doc for `:Rename`, however I think this would be alot more useful and intuitive if it worked as described (always relative to dir of current file/buf). If I wanted the other behavior, I'd be using `:Move` instead of `:Rename` in the first place.
