### ISSUE TITLE
SudoWrite is stuck after typing password

### ISSUE THREAD

**Issue by doronbehar** [tpope/vim-eunuch#45]
I get this weird behavior: After typing the password and pressing `Enter`, the shell seems to be stuck and I have to press <C-c> a few times in order to stop it, Afterwards the file is not saved and I don't gain sudo permissions. I tried change the `function! s:SudoWriteCmd()` and it worked, but it seems weird to make a pull request about it because I don't know what doesn't work in the original function.
my version for the function is as follow:

``` vim
function! s:SudoWriteCmd() abort
  execute (has('gui_running') ? '' : 'silent') 'write !sudo tee "%"'
  let &modified = v:shell_error
endfunction
```

And your version for the execute command is:

``` vim
  execute (has('gui_running') ? '' : 'silent') 'write !env SUDO_EDITOR=tee VISUAL=tee sudo -e "%" >/dev/null'
```

What is the purpose of `> /dev/null`? Why wouldn't you keep it simple like in my version?

**Comment by hiberabyss** [comment]
I have the same problem.

**Comment by tpope** [comment]
I think we could probably drop the `>/dev/null` when `silent` is given (i.e., when the gui is running), if that helps.

**Comment by tpope** [comment]
To answer the actual questions:

1. Depending on the terminal of lack thereof, omitting `>/dev/null` can allow the entire file to be flooded to stdout, sometimes visible as flickering. Dropping it is not necessarily a deal breaker.
2. The rest of the construct is to use `sudoedit` permissions rather than `tee`. See `--edit` in sudo(8).

**Comment by doronbehar** [comment]
I'm not sure how to start implementing this myself but it crossed my mind that perhaps it could be possible to use `su -c` instead of `sudo`. Would that break any other features?

**Comment by tpope** [comment]
Well `su` is a completely different security model, requiring the root password rather than the user password. I could maybe see supporting it as a fallback, if people actually want that sort of thing, but I don't see it as a solution to the hanging problem.

On a related note, I did switch things up to use `-A` (`--askpass`) in the GUI, which I think is probably a better solution to your problem? Assuming you're experiencing the problem in a GUI Vim.

**Comment by doronbehar** [comment]
To tell the truth, The problem was experienced with neovim and without
GUI.

**Comment by tpope** [comment]
Oh that's a whole nother kettle of fish. Neovim essentially forces you to use `:terminal` for any interactive command, and I doubt that's an option in `BufReadCmd`. I don't understand why your proposed fix in the original issue would help, but I could easily be missing something.

**Comment by kiooss** [comment]
The neovim issue is this https://github.com/neovim/neovim/issues/1716 .
But strangely `:SudoWrite` works in neovim on my Ubuntu but not macOS version.

**Comment by tpope** [comment]
I just changed it use `-A` for local Neovim instances, which might work around the problem.
