### ISSUE TITLE
SudoWrite not working in neovim

### ISSUE THREAD

**Issue by eskinderg** [tpope/vim-eunuch#56]
I have used the SudoWrite functionality and have saved me so much time.
Recently i am not sure why i am get the following message when i do the SudoWrite.

```
Error detected while processing BufWriteCmd Auto commands for "/etc/systemd/logind.conf":
sudo: no tty present and no askpass program specified
```

Below is my neovim version.
:version
NVIM v0.3.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by randomizedthinking** [comment]
It is a known issue in neovim: https://github.com/neovim/neovim/issues/8527. The conclusion is not-to-fix since the current vim approach can create other unpleasant problems too -- it is just trade-off.

You can use: https://github.com/lambdalisue/suda.vim. It would be nice if @tpope can incorporate it to vim-eunuch.

**Comment by tpope** [comment]
Handling the password ourselves makes me a bit squeamish but I I can't think of a practical objection.

**Comment by rdnetto** [comment]
This is caused by https://github.com/neovim/neovim/issues/8217. https://github.com/lambdalisue/suda.vim demonstrates one workaround for it (explicitly reading the password with `inputsecret()` and piping it in with `sudo --stdin`), which suffers from a few weaknesses compared to vim-eunuch's current implementation (password is temporarily stored in Vim, password must be re-entered multiple times).

Another more secure, but less portable, workaround is to just use netrw to edit the file over SSH via `root@localhost`, assuming you the daemon running and your public key in root's `authorized_hosts` file.

(Hopefully there's a better solution than either of these, but I'll leave that to someone who knows more than me)

**Comment by tpope** [comment]
Oh, the re-entering of the password is a pretty huge compromise.

**Comment by Trollwut** [comment]
stupid question: so currently `SudoWrite` doesn't work in neovim?

**Comment by tpope** [comment]
It works if you have `$SUDO_ASKPASS` set, or `Path askpass` configured in `/etc/sudo.conf`.

**Comment by TSFoster** [comment]
Leaving this here in case it is of any use to people using macOS + nvim. There might be better ways, but here is how I got it to work:

1. Create file `macos-askpass`:
    
    ```js
    #!/usr/bin/env osascript -l JavaScript
    
    var app = Application.currentApplication();
    app.includeStandardAdditions = true;
    app.displayDialog("Enter password:", { hiddenAnswer: true, defaultAnswer: "" }).textReturned;
    ```
2. `chmod +x /path/to/macos-askpass`
3. Set `$SUDO_ASKPASS` to `/path/to/macos-askpass` (I do this in my `init.vim` with `let $SUDO_ASKPASS="/path/to/macos-askpass"`)
