### ISSUE TITLE
Error detected while processing BufWriteCmd Auto Commands

### ISSUE THREAD

**Issue by markfaine** [tpope/vim-eunuch#57]
I get this error when I do SudoWrite.

See the attached 
![error](https://user-images.githubusercontent.com/949949/49229911-1f530f00-f3b4-11e8-8f35-553108fa4aa8.png)
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 10 2018 23:54:40)
on CentOS Linux release 7.5.1804 (Core)

**Comment by markfaine** [comment]
I've discovered the cause and a workaround, but I be interested to know your thoughts and if there is anyway to workaround it in the plugin without modifying sudoers.

https://www.smarinov.com/weblog/sudoedit-not-working/

**Comment by markfaine** [comment]
No, just the error.  For now, I added !sudoedit_checkdir to Defaults in sudoers but I'd rather not have to do that everywhere.  Thanks

**Comment by tpope** [comment]
I think i'm gonna classify this as wontfix. A file in a writable directory could just as easily be removed and recreated. You may as make the file writable too, because the security gained by making it read only is literally zero. I think `sudo` trying to do you a favor, and I would need a good reason to override it.

Related: #34
