### ISSUE TITLE
Add :DeleteDir command

### ISSUE THREAD

**Issue by anh072** [tpope/vim-eunuch#58]
it seems to me that :Delete only deletes a file.
It would be nice if we can have recursive :Delete to remove a directory and its files

**Comment by izelnakri** [comment]
I was just going to suggest the same! We can delete the directory if no files exists anymore in the directory.

Also it would be useful to make :e mkdir -p aware: https://github.com/duggiefresh/vim-easydir/blob/master/plugin/easydir.vim

**Comment by tpope** [comment]
I think having a command that calls `rm -rf` has more downside than upside, but making `:Delete` call `rmdir` on directories would be swell.

Vim behaves really strange when editing a file in a non-existent directory - note what happens when you `:cd` for example. Creating the directory on write is a half measure that will likely end up burning you at some point. (And the guard in that plugin is laughably bad: a whitelist will always miss things but this one doesn't even include `https`.)
