### ISSUE TITLE
Error on :SudoWrite

### ISSUE THREAD

**Issue by kuntau** [tpope/vim-eunuch#69]
```
Error detected while processing BufWriteCmd Autocommands for "/etc/fstab":
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```

I don't get any prompt for password 🤔 
`Ubuntu 20.04`

**Comment by Shatur95** [comment]
I have the same issue.

**Comment by vianpl** [comment]
Same here.

**Comment by Shatur95** [comment]
I found the solution. This is not the plugin issue. Just need set `SUDO_ASKPASS`. In KDE you need `ksshaskpass`.

**Comment by Shane-XB-Qian** [comment]
it's using 'sudo -e' vs directly 'sudo', so looks a bit complex or req more config if so..
// ':Mkdir' worked perfectly at least.. :)

**Comment by tpope** [comment]
`SUDO_ASKPASS` or the appropriate `sudo.conf` config is the correct solution. `sudo -e` isn't any different from `sudo` when it comes to this.

**Comment by Shane-XB-Qian** [comment]
um.. yes, i mean it req extra config actually.. though perhaps directly relevant..
e.g:
```txt
:SudoWrite
Error detected while processing BufWriteCmd Autocommands for "/home/shane/x.txt":
sudo: x.txt: editing files in a writable directory is not permitted
```

**Comment by tpope** [comment]
Separate issue from password entry, but I must admit I was not aware of the writable directory limitation of `sudo -e`. It would be easy enough to use `tee` directly in that case, but do we really want to? It seems like a valid security restriction.

**Comment by Shane-XB-Qian** [comment]
yes, but not sure if it was new (new security restriction), i used to use 'sudo tee' directly actually..
looks had to set a dirchecker setting into sudo config to bypass it, or sth else..
// anyway what i meant was: if using 'sudo -e' then there were some extra config needed to handle, or ':SudoWrite' actually was not working..
// anyway had much/enough security check actually was good, since we are doing 'root' authority.. it's risky.. but just not sure if ':SudoWrite' was able to handle all those security check.. :)
